CREATE TABLE student
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name             VARCHAR(255),
    second_name            VARCHAR(255),
    last_name              VARCHAR(255),
    email                  VARCHAR(255),
    phone_number           VARCHAR(255),
    city                   VARCHAR(255),
    diploma                BOOLEAN,
    technical_skills       VARCHAR(255),
    english_level          SMALLINT,
    work_experience        INTEGER,
    programming_experience INTEGER,
    courses_experience     INTEGER,
    CONSTRAINT pk_student PRIMARY KEY (id)
);