CREATE TABLE rate
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_id                BIGINT,
    diploma                   SMALLINT,
    programming_experience    SMALLINT,
    stack                     SMALLINT,
    programming_participation SMALLINT,
    majorit                   SMALLINT,
    english_level             SMALLINT,
    CONSTRAINT pk_rate PRIMARY KEY (id)
);

CREATE TABLE student
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name                 VARCHAR(255),
    email                     VARCHAR(255),
    phone_number              VARCHAR(255),
    diploma                   BOOLEAN,
    com_exp                   BOOLEAN,
    programming_exp           INTEGER,
    programming_participation BOOLEAN,
    stack                     INTEGER,
    majorit                   BOOLEAN,
    english_level             INTEGER,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE rate
    ADD CONSTRAINT FK_RATE_ON_STUDENT FOREIGN KEY (student_id) REFERENCES student (id);